### ISSUE TITLE
How can I make zsh aliases available when shelling out from Vim?

### ISSUE THREAD

**Issue by brianleppez** [z0rc/dotfiles#1963]
I want to use your custom alias `bag` from within Vim but it doesn't work. I get a `command: not found: bag` result. 

How do you achieve this?

**Comment by z0rc** [comment]
I don't think it's achievable as is. `bag` is shell function, so in order to call it one need an interactive shell session.

You have two options here:
* make `bag` into shell script, probably not that hard
* use https://github.com/junegunn/fzf.vim, as technically `bag` is just shell implementation of `:Ag` command from this plugin

**Comment by brianleppez** [comment]
Okay I understand. Can you describe your workflow when you're in Vim and want search a file for a given string and open it in Vim?

**Comment by z0rc** [comment]
`:Ag` command from https://github.com/junegunn/fzf.vim.
